// 游戏数据 - 包含50款游戏信息
const games = [
  {
    id: 1,
    title: "赛博朋克2077",
    genre: ["角色扮演", "动作"],
    developer: "CD Projekt Red",
    releaseYear: 2020,
    rating: 4.5,
    description: "一款开放世界动作冒险角色扮演游戏，故事发生在夜之城。",
    image: "https://cdn.akamai.steamstatic.com/steam/apps/1091500/header.jpg",
    officialWebsite: "https://www.cyberpunk.net"
  },
  {
    id: 2,
    title: "艾尔登法环",
    genre: ["动作", "角色扮演"],
    developer: "FromSoftware",
    releaseYear: 2022,
    rating: 4.8,
    description: "以正统黑暗奇幻世界为舞台的动作RPG游戏。",
    image: "https://cdn.akamai.steamstatic.com/steam/apps/1245620/header.jpg",
    officialWebsite: "https://www.bandainamcoent.com/games/elden-ring"
  },
  {
    id: 3,
    title: "我的世界",
    genre: ["沙盒", "生存"],
    developer: "Mojang Studios",
    releaseYear: 2011,
    rating: 4.7,
    description: "一个关于放置方块和冒险的游戏。",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.minecraft.net"
  },
  {
    id: 4,
    title: "英雄联盟",
    genre: ["MOBA", "多人"],
    developer: "Riot Games",
    releaseYear: 2009,
    rating: 4.3,
    description: "一款多人在线战术竞技游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.leagueoflegends.com"
  },
  {
    id: 5,
    title: "巫师3：狂猎",
    genre: ["角色扮演", "动作", "冒险"],
    developer: "CD Projekt Red",
    releaseYear: 2015,
    rating: 4.9,
    description: "扮演职业猎魔人利维亚的杰洛特，四处狩猎野兽。",
    image: "https://cdn.akamai.steamstatic.com/steam/apps/292030/header.jpg",
    officialWebsite: "https://thewitcher.com/en/witcher3"
  },
  {
    id: 6,
    title: "Apex Legends",
    genre: ["射击", "大逃杀"],
    developer: "Respawn Entertainment",
    releaseYear: 2019,
    rating: 4.4,
    description: "免费的英雄射击大逃杀游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.ea.com/games/apex-legends"
  },
  {
    id: 7,
    title: "最终幻想XIV",
    genre: ["角色扮演", "MMO"],
    developer: "Square Enix",
    releaseYear: 2013,
    rating: 4.6,
    description: "备受好评的大型多人在线角色扮演游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.finalfantasyxiv.com"
  },
  {
    id: 8,
    title: "反恐精英2",
    genre: ["射击", "多人"],
    developer: "Valve",
    releaseYear: 2023,
    rating: 4.2,
    description: "经典的战术射击游戏最新版本。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.counter-strike.net"
  },
  {
    id: 9,
    title: "星露谷物语",
    genre: ["模拟", "角色扮演"],
    developer: "ConcernedApe",
    releaseYear: 2016,
    rating: 4.8,
    description: "在星露谷开始你的农场生活。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.stardewvalley.net"
  },
  {
    id: 10,
    title: "塞尔达传说：王国之泪",
    genre: ["动作", "冒险"],
    developer: "Nintendo",
    releaseYear: 2023,
    rating: 4.9,
    description: "林克与塞尔达的新冒险，探索海拉鲁大地。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.zelda.com/tears-of-the-kingdom"
  },
  {
    id: 11,
    title: "刺客信条：幻景",
    genre: ["动作", "冒险"],
    developer: "Ubisoft",
    releaseYear: 2023,
    rating: 4.3,
    description: "回到刺客信条系列的本源，体验巴格达的故事。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.ubisoft.com/games/assassins-creed/mirage"
  },
  {
    id: 12,
    title: "博德之门3",
    genre: ["角色扮演", "策略"],
    developer: "Larian Studios",
    releaseYear: 2023,
    rating: 4.9,
    description: "基于龙与地下城规则的史诗级角色扮演游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://baldursgate3.game"
  },
  {
    id: 13,
    title: "霍格沃茨之遗",
    genre: ["动作", "角色扮演"],
    developer: "Avalanche Software",
    releaseYear: 2023,
    rating: 4.5,
    description: "在霍格沃茨魔法学校体验魔法世界。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.hogwartslegacy.com"
  },
  {
    id: 14,
    title: "极限竞速：地平线5",
    genre: ["竞速", "模拟"],
    developer: "Playground Games",
    releaseYear: 2021,
    rating: 4.7,
    description: "在美丽的墨西哥开放世界中进行赛车冒险。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://forza.net/horizon"
  },
  {
    id: 15,
    title: "漫威蜘蛛侠2",
    genre: ["动作", "冒险"],
    developer: "Insomniac Games",
    releaseYear: 2023,
    rating: 4.8,
    description: "扮演蜘蛛侠，在纽约市打击犯罪。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://insomniac.games/game/marvels-spider-man-2"
  },
  {
    id: 16,
    title: "动物森友会",
    genre: ["模拟", "生活"],
    developer: "Nintendo",
    releaseYear: 2020,
    rating: 4.8,
    description: "在无人岛上开始新的生活。",
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.animal-crossing.com/new-horizons"
  },
  {
    id: 17,
    title: "火箭联盟",
    genre: ["体育", "竞速"],
    developer: "Psyonix",
    releaseYear: 2015,
    rating: 4.4,
    description: "用火箭车踢足球的独特游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.rocketleague.com"
  },
  {
    id: 18,
    title: "命运2",
    genre: ["射击", "MMO"],
    developer: "Bungie",
    releaseYear: 2017,
    rating: 4.3,
    description: "免费的在线第一人称射击游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.bungie.net/7/en/Destiny"
  },
  {
    id: 19,
    title: "上古卷轴V：天际",
    genre: ["角色扮演", "动作"],
    developer: "Bethesda",
    releaseYear: 2011,
    rating: 4.8,
    description: "在广阔的天际省体验史诗冒险。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://elderscrolls.bethesda.net/en/skyrim"
  },
  {
    id: 20,
    title: "只狼：影逝二度",
    genre: ["动作", "冒险"],
    developer: "FromSoftware",
    releaseYear: 2019,
    rating: 4.7,
    description: "战国题材的高难度动作游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.sekirothegame.com"
  },
  {
    id: 21,
    title: "荒野大镖客2",
    genre: ["动作", "冒险"],
    developer: "Rockstar Games",
    releaseYear: 2018,
    rating: 4.9,
    description: "在美国西部展开的史诗冒险。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.rockstargames.com/reddeadredemption2"
  },
  {
    id: 22,
    title: "黑暗之魂3",
    genre: ["动作", "角色扮演"],
    developer: "FromSoftware",
    releaseYear: 2016,
    rating: 4.7,
    description: "高难度的动作角色扮演游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.bandainamcoent.com/games/dark-souls-iii"
  },
  {
    id: 23,
    title: "守望先锋2",
    genre: ["射击", "多人"],
    developer: "Blizzard Entertainment",
    releaseYear: 2022,
    rating: 4.1,
    description: "团队为基础的英雄射击游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://overwatch.blizzard.com"
  },
  {
    id: 24,
    title: "尼尔：自动人形",
    genre: ["动作", "角色扮演"],
    developer: "PlatinumGames",
    releaseYear: 2017,
    rating: 4.8,
    description: "末世题材的动作角色扮演游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.niergame.com"
  },
  {
    id: 25,
    title: "怪物猎人：世界",
    genre: ["动作", "角色扮演"],
    developer: "Capcom",
    releaseYear: 2018,
    rating: 4.7,
    description: "狩猎各种巨兽的动作游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.monsterhunter.com/world"
  },
  {
    id: 26,
    title: "双人成行",
    genre: ["冒险", "合作"],
    developer: "Hazelight Studios",
    releaseYear: 2021,
    rating: 4.9,
    description: "专为合作设计的冒险游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.ea.com/games/it-takes-two"
  },
  {
    id: 27,
    title: "鬼泣5",
    genre: ["动作", "冒险"],
    developer: "Capcom",
    releaseYear: 2019,
    rating: 4.6,
    description: "华丽的动作砍杀游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.devilmaycry5.com"
  },
  {
    id: 28,
    title: "生化危机4 重制版",
    genre: ["动作", "恐怖"],
    developer: "Capcom",
    releaseYear: 2023,
    rating: 4.8,
    description: "经典生存恐怖游戏的重制版。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.residentevil.com/re4"
  },
  {
    id: 29,
    title: "战神",
    genre: ["动作", "冒险"],
    developer: "Santa Monica Studio",
    releaseYear: 2018,
    rating: 4.9,
    description: "北欧神话背景的动作冒险游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.playstation.com/games/god-of-war"
  },
  {
    id: 30,
    title: "哈迪斯",
    genre: ["动作", "角色扮演"],
    developer: "Supergiant Games",
    releaseYear: 2020,
    rating: 4.8,
    description: "希腊神话背景的roguelike动作游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.supergiantgames.com/games/hades"
  },
  {
    id: 31,
    title: "空洞骑士",
    genre: ["动作", "冒险"],
    developer: "Team Cherry",
    releaseYear: 2017,
    rating: 4.8,
    description: "手绘风格的类银河战士恶魔城游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.hollowknight.com"
  },
  {
    id: 32,
    title: "泰拉瑞亚",
    genre: ["沙盒", "冒险"],
    developer: "Re-Logic",
    releaseYear: 2011,
    rating: 4.8,
    description: "2D沙盒建造和冒险游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://terraria.org"
  },
  {
    id: 33,
    title: "蔚蓝",
    genre: ["平台", "冒险"],
    developer: "Maddy Makes Games",
    releaseYear: 2018,
    rating: 4.8,
    description: "挑战性的平台跳跃游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.celestegame.com"
  },
  {
    id: 34,
    title: "毁灭战士：永恒",
    genre: ["射击", "动作"],
    developer: "id Software",
    releaseYear: 2020,
    rating: 4.6,
    description: "快节奏的第一人称射击游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://slayersclub.bethesda.net"
  },
  {
    id: 35,
    title: "控制",
    genre: ["动作", "冒险"],
    developer: "Remedy Entertainment",
    releaseYear: 2019,
    rating: 4.5,
    description: "超自然题材的第三人称动作游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.controlgame.com"
  },
  {
    id: 36,
    title: "死亡搁浅",
    genre: ["动作", "冒险"],
    developer: "Kojima Productions",
    releaseYear: 2019,
    rating: 4.4,
    description: "小岛秀夫打造的连接主题游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.kojimaproductions.jp/en/games/death-stranding"
  },
  {
    id: 37,
    title: "仁王2",
    genre: ["动作", "角色扮演"],
    developer: "Team Ninja",
    releaseYear: 2020,
    rating: 4.6,
    description: "战国诛死游戏，挑战高难度战斗。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.teamninja-studio.com/nioh2"
  },
  {
    id: 38,
    title: "星球大战绝地：幸存者",
    genre: ["动作", "冒险"],
    developer: "Respawn Entertainment",
    releaseYear: 2023,
    rating: 4.5,
    description: "扮演卡尔·凯斯提斯，体验星球大战冒险。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.ea.com/games/starwars/jedi/jedi-survivor"
  },
  {
    id: 39,
    title: "盗贼之海",
    genre: ["冒险", "多人"],
    developer: "Rare",
    releaseYear: 2018,
    rating: 4.3,
    description: "海盗主题的多人冒险游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.seaofthieves.com"
  },
  {
    id: 40,
    title: "糖豆人",
    genre: ["休闲", "多人"],
    developer: "Mediatonic",
    releaseYear: 2020,
    rating: 4.2,
    description: "多人乱斗的闯关综艺游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.fallguys.com"
  },
  {
    id: 41,
    title: "饥荒",
    genre: ["生存", "冒险"],
    developer: "Klei Entertainment",
    releaseYear: 2013,
    rating: 4.7,
    description: "在荒野中生存的冒险游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.kleientertainment.com/games/dont-starve"
  },
  {
    id: 42,
    title: "欧洲卡车模拟2",
    genre: ["模拟", "驾驶"],
    developer: "SCS Software",
    releaseYear: 2012,
    rating: 4.7,
    description: "驾驶卡车穿越欧洲的模拟游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.eurotrucksimulator2.com"
  },
  {
    id: 43,
    title: "文明6",
    genre: ["策略", "回合制"],
    developer: "Firaxis Games",
    releaseYear: 2016,
    rating: 4.5,
    description: "建立帝国，经得起时间考验的策略游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.civilization.com"
  },
  {
    id: 44,
    title: "城市：天际线",
    genre: ["模拟", "策略"],
    developer: "Colossal Order",
    releaseYear: 2015,
    rating: 4.6,
    description: "现代城市模拟游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.citiesskylines.com"
  },
  {
    id: 45,
    title: "全面战争：三国",
    genre: ["策略", "回合制"],
    developer: "Creative Assembly",
    releaseYear: 2019,
    rating: 4.7,
    description: "基于三国时期的策略游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.totalwar.com/games/three-kingdoms"
  },
  {
    id: 46,
    title: "雨中冒险2",
    genre: ["动作", "roguelike"],
    developer: "Hopoo Games",
    releaseYear: 2020,
    rating: 4.8,
    description: "第三人称的roguelike射击游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://riskofrain.com"
  },
  {
    id: 47,
    title: "杀戮尖塔",
    genre: ["策略", "roguelike"],
    developer: "Mega Crit Games",
    releaseYear: 2019,
    rating: 4.8,
    description: "卡牌构建的roguelike游戏。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.megacrit.com"
  },
  {
    id: 48,
    title: "异度神剑3",
    genre: ["角色扮演", "动作"],
    developer: "Monolith Soft",
    releaseYear: 2022,
    rating: 4.7,
    description: "史诗级角色扮演游戏。",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    officialWebsite: "https://www.nintendo.com/games/detail/xenoblade-chronicles-3"
  },
  {
    id: 49,
    title: "火焰纹章：风花雪月",
    genre: ["策略", "角色扮演"],
    developer: "Intelligent Systems",
    releaseYear: 2019,
    rating: 4.8,
    description: "战棋策略与角色扮演结合的游戏。",
    image: "https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&h=300&fit=crop",
    officialWebsite: "https://www.nintendo.com/games/detail/fire-emblem-three-houses"
  },
  {
    id: 50,
    title: "猎天使魔女3",
    genre: ["动作", "冒险"],
    developer: "PlatinumGames",
    releaseYear: 2022,
    rating: 4.6,
    description: "华丽动作游戏的最新续作。",
    image: "https://images.unsplash.com/photo-1552820728-8b83bb6b773f?w=400&h=300&fit=crop",
    officialWebsite: "https://www.nintendo.com/games/detail/bayonetta-3"
  }
];

// 游戏类型
const gameGenres = [
  "全部类型", "角色扮演", "动作", "沙盒", "MOBA", 
  "射击", "冒险", "生存", "大逃杀", "多人", "策略",
  "模拟", "恐怖", "竞速", "体育", "休闲", "roguelike",
  "MMO", "合作", "平台", "回合制", "生活", "驾驶"
];